In [16]:

#import config
#import psycopg2
from config import *

import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, MetaData, Table

import sqlalchemy

engine = sqlalchemy.create_engine(database_url)
connection = engine.connect()

# Declare a Base using `automap_base()`
Base = automap_base()
# Use the Base class to reflect the database tables
Base.prepare(engine, reflect=True)
# Print all of the classes mapped to the Base
Base.classes.keys()

['confirmed_planets1']

### Method 1: Pandas

In [17]:
import pandas as pd

In [15]:
planets_df = pd.read_sql_table('confirmed_planets1', engine)
planets_df

,planet_name,planet_mass,planet_radius,distance,host_name,koi_name,exoplanet_archive_disposition,orbital_period,transit_epoch,impact_parameter,...,equilibrium_temperature,insolation_flux,transit_signal_to_noise,tce_planet_number,stellar_effective_temperature,stellar_surface_gravity,stellar_radius,ra,decimal_degrees,kepler_band
0,Kepler-10 b,4.60853,1.481,185.506,Kepler-10,K00072.01,CONFIRMED,0.837491,131.574858,0.022,...,1980.0,3630.32,189.5,2.0,5676.0,4.347,1.044,285.67938,50.241299,10.961
1,Kepler-10 c,7.37000,2.323,185.506,Kepler-10,K00072.02,CONFIRMED,45.294223,138.678725,0.025,...,524.0,17.75,134.8,1.0,5676.0,4.347,1.044,285.67938,50.241299,10.961
2,Kepler-100 b,7.34000,1.320,304.645,Kepler-100,K00041.02,CONFIRMED,6.887071,133.177970,0.696,...,1155.0,420.97,38.2,2.0,5788.0,4.122,1.474,291.38599,41.990269,11.197
3,Kepler-100 c,7.05000,2.200,304.645,Kepler-100,K00041.01,CONFIRMED,12.815904,122.946820,0.580,...,939.0,183.68,106.7,1.0,5788.0,4.122,1.474,291.38599,41.990269,11.197
4,Kepler-100 d,3.00000,1.610,304.645,Kepler-100,K00041.03,CONFIRMED,35.333193,153.982490,0.656,...,670.0,47.52,28.8,3.0,5788.0,4.122,1.474,291.38599,41.990269,11.197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2615,Kepler-995 b,7.75000,2.700,609.638,Kepler-995,K01881.01,CONFIRMED,28.267274,140.925610,0.010,...,517.0,16.84,42.1,1.0,5132.0,4.457,0.886,284.61572,39.131039,14.907
2616,Kepler-996 b,4.58000,1.980,1216.580,Kepler-996,K01882.01,CONFIRMED,3.770591,133.390880,0.240,...,1272.0,619.65,37.1,1.0,5714.0,4.274,1.208,291.91281,41.533611,14.668
2617,Kepler-997 b,2.42000,1.360,467.568,Kepler-997,K01883.01,CONFIRMED,2.707306,132.430680,0.007,...,1709.0,2012.12,31.7,1.0,6045.0,4.069,1.629,289.23337,49.938931,11.894
2618,Kepler-998 b,5.99000,2.320,986.364,Kepler-998,K01885.01,CONFIRMED,5.653782,131.711540,0.439,...,1020.0,256.14,37.8,1.0,5988.0,4.507,0.934,296.75415,49.208740,14.377
2619,Kepler-999 b,6.08000,2.340,545.063,Kepler-999,K01886.01,CONFIRMED,5.991858,136.882440,0.905,...,1355.0,796.76,32.1,1.0,6157.0,4.049,1.695,299.66046,46.198421,12.239

In [5]:
metadata = MetaData()

In [6]:
# Create a table object and use 'autoload' and 'autoload_with' to define the columns from the table. 
table = Table('confirmed_planets1', metadata, autoload=True, autoload_with=engine)

In [7]:
# Get the column names using the 'keys()' method on the column object. 
table.columns.keys()

['planet_name',
 'planet_mass',
 'planet_radius',
 'distance',
 'host_name',
 'koi_name',
 'exoplanet_archive_disposition',
 'orbital_period',
 'transit_epoch',
 'impact_parameter',
 'transit_duration',
 'transit_depth',
 'planetary_radius',
 'equilibrium_temperature',
 'insolation_flux',
 'transit_signal_to_noise',
 'tce_planet_number',
 'stellar_effective_temperature',
 'stellar_surface_gravity',
 'stellar_radius',
 'ra',
 'decimal_degrees',
 'kepler_band']

In [8]:
table.columns.orbital_period

Column('orbital_period', DOUBLE_PRECISION(precision=53), table=<confirmed_planets1>)

In [ ]:
connection.close()

In [9]:
# scrap code
conn = psycopg2.connect(dbname=DB_NAME, user=DB_USER, password=DB_PASS, host=DB_HOST, port=5432)
#conn = psycopg2.connect(dbname=DB_NAME, user=DB_USER, password=DB_PASS, host=DB_HOST, port=5432)
cur = conn.cursor()
cur.execute("SELECT * FROM confirmed_planets1;")
print(cur.fetchall())
conn.commit()

OperationalError: could not translate host name "postgresql://Brute_Force:daisy_mozart_chorizo@exoplanets1.c8rvp46kd4vt.us-east-1.rds.amazonaws.com/confirmed_planets1" to address: nodename nor servname provided, or not known

In [1]:
cur.close()
conn.close()

NameError: name 'cur' is not defined

In [10]:
inspector = inspect(engine)

In [11]:
data = engine.execute("SELECT * FROM confirmed_planets1 limit 10")

for record in data:
    print(record)

('Kepler-10 b', 4.60853, 1.481, 185.506, 'Kepler-10', 'K00072.01', 'CONFIRMED', 0.837491225, 131.574858, 0.022, 1.796, 190.4, 1.43, 1980.0, 3630.32, 189.5, 2.0, 5676.0, 4.347, 1.044, 285.67938, 50.241299, 10.961)
('Kepler-10 c', 7.37, 2.323, 185.506, 'Kepler-10', 'K00072.02', 'CONFIRMED', 45.29422297, 138.678725, 0.025, 6.83, 477.1, 2.26, 524.0, 17.75, 134.8, 1.0, 5676.0, 4.347, 1.044, 285.67938, 50.241299, 10.961)
('Kepler-100 b', 7.34, 1.32, 304.645, 'Kepler-100', 'K00041.02', 'CONFIRMED', 6.88707073, 133.17797, 0.696, 4.4679, 68.7, 1.3, 1155.0, 420.97, 38.2, 2.0, 5788.0, 4.122, 1.474, 291.38599, 41.990269, 11.197)
('Kepler-100 c', 7.05, 2.2, 304.645, 'Kepler-100', 'K00041.01', 'CONFIRMED', 12.81590421, 122.94682, 0.58, 6.3856, 220.5, 2.26, 939.0, 183.68, 106.7, 1.0, 5788.0, 4.122, 1.474, 291.38599, 41.990269, 11.197)
('Kepler-100 d', 3.0, 1.61, 304.645, 'Kepler-100', 'K00041.03', 'CONFIRMED', 35.3331932, 153.98249, 0.656, 5.966, 99.7, 1.55, 670.0, 47.52, 28.8, 3.0, 5788.0, 4.122, 1.474, 291.38599, 41.990269, 11.197)
('Kepler-1000 b', 20.3, 4.76, 1115.62, 'Kepler-1000', 'K01888.01', 'CONFIRMED', 120.0183551, 134.18742, 0.58, 11.637, 886.0, 4.54, 473.0, 11.84, 46.1, 1.0, 6469.0, 4.253, 1.467, 286.68552, 47.098221, 13.256)
('Kepler-1001 b', 10.1, 3.15, 928.978, 'Kepler-1001', 'K01889.01', 'CONFIRMED', 14.30517579, 135.06301, 0.924, 4.535, 863.4, 3.05, 693.0, 54.59, 37.5, 1.0, 5741.0, 4.555, 0.846, 286.27386, 48.61871, 15.338)
('Kepler-1001 c', 3.11, 1.578, 928.978, 'Kepler-1001', 'K01889.02', 'CONFIRMED', 9.18189122, 132.40505, 0.971, 4.343, 363.6, 2.17, 804.0, 98.61, 18.2, 2.0, 5741.0, 4.555, 0.846, 286.27386, 48.61871, 15.338)
('Kepler-1002 b', 3.57, 1.71, 408.303, 'Kepler-1002', 'K01890.01', 'CONFIRMED', 4.33643506, 133.85442, 0.641, 4.1445, 108.5, 1.75, 1453.0, 1054.56, 48.0, 1.0, 6180.0, 4.133, 1.603, 293.0795, 43.073711, 11.704)
('Kepler-1003 b', 3.82, 1.78, 941.902, 'Kepler-1003', 'K01893.01', 'CONFIRMED', 3.554856338, 131.80398, 0.331, 2.1004, 232.9, 1.29, 1157.0, 425.04, 40.8, 1.0, 6068.0, 4.565, 0.831, 292.02045, 44.876221, 14.053)

In [12]:
columns = inspector.get_columns('confirmed_planets1')
for column in columns:
    print(column["name"], column["type"])

planet_name VARCHAR(50)
planet_mass DOUBLE_PRECISION
planet_radius DOUBLE_PRECISION
distance DOUBLE_PRECISION
host_name VARCHAR(50)
koi_name VARCHAR(50)
exoplanet_archive_disposition VARCHAR(50)
orbital_period DOUBLE_PRECISION
transit_epoch DOUBLE_PRECISION
impact_parameter DOUBLE_PRECISION
transit_duration DOUBLE_PRECISION
transit_depth DOUBLE_PRECISION
planetary_radius DOUBLE_PRECISION
equilibrium_temperature DOUBLE_PRECISION
insolation_flux DOUBLE_PRECISION
transit_signal_to_noise DOUBLE_PRECISION
tce_planet_number DOUBLE_PRECISION
stellar_effective_temperature DOUBLE_PRECISION
stellar_surface_gravity DOUBLE_PRECISION
stellar_radius DOUBLE_PRECISION
ra DOUBLE_PRECISION
decimal_degrees DOUBLE_PRECISION
kepler_band DOUBLE_PRECISION