In [7]:

#import config
#import psycopg2
from config import *

import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, MetaData, Table

import sqlalchemy
import json

engine = sqlalchemy.create_engine(database_url)
connection = engine.connect()

# Declare a Base using `automap_base()`
Base = automap_base()
# Use the Base class to reflect the database tables
Base.prepare(engine, reflect=True)
# Print all of the classes mapped to the Base
Base.classes.keys()

['confirmed_planets1', 'orbital_radius', 'false_planets']

In [4]:
import pandas as pd

In [11]:
df=pd.read_sql_table('confirmed_planets1', engine)
df.head()

,planet_name,planet_mass,planet_radius,distance,host_name,koi_name,exoplanet_archive_disposition,orbital_period,transit_epoch,impact_parameter,...,equilibrium_temperature,insolation_flux,transit_signal_to_noise,tce_planet_number,stellar_effective_temperature,stellar_surface_gravity,stellar_radius,ra,decimal_degrees,kepler_band
0,Kepler-10 b,4.60853,1.481,185.506,Kepler-10,K00072.01,CONFIRMED,0.837491,131.574858,0.022,...,1980.0,3630.32,189.5,2.0,5676.0,4.347,1.044,285.67938,50.241299,10.961
1,Kepler-10 c,7.37000,2.323,185.506,Kepler-10,K00072.02,CONFIRMED,45.294223,138.678725,0.025,...,524.0,17.75,134.8,1.0,5676.0,4.347,1.044,285.67938,50.241299,10.961
2,Kepler-100 b,7.34000,1.320,304.645,Kepler-100,K00041.02,CONFIRMED,6.887071,133.177970,0.696,...,1155.0,420.97,38.2,2.0,5788.0,4.122,1.474,291.38599,41.990269,11.197
3,Kepler-100 c,7.05000,2.200,304.645,Kepler-100,K00041.01,CONFIRMED,12.815904,122.946820,0.580,...,939.0,183.68,106.7,1.0,5788.0,4.122,1.474,291.38599,41.990269,11.197
4,Kepler-100 d,3.00000,1.610,304.645,Kepler-100,K00041.03,CONFIRMED,35.333193,153.982490,0.656,...,670.0,47.52,28.8,3.0,5788.0,4.122,1.474,291.38599,41.990269,11.197

In [12]:
df.columns

Index(['planet_name', 'planet_mass', 'planet_radius', 'distance', 'host_name',
       'koi_name', 'exoplanet_archive_disposition', 'orbital_period',
       'transit_epoch', 'impact_parameter', 'transit_duration',
       'transit_depth', 'planetary_radius', 'equilibrium_temperature',
       'insolation_flux', 'transit_signal_to_noise', 'tce_planet_number',
       'stellar_effective_temperature', 'stellar_surface_gravity',
       'stellar_radius', 'ra', 'decimal_degrees', 'kepler_band'],
      dtype='object')